/*
 * Pinnacle - Customer API Reference
 *
 *  # Authentication   API uses HTTP Basic access authentication. You need to send Authorization HTTP Request header:    `Authorization: Basic <Base64 value of UTF-8 encoded \"username:password\">`  Example:  `Authorization: Basic U03MyOT23YbzMDc6d3c3O1DQ1`
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pinapi

import (
	"bytes"
	"encoding/json"
)

// OddsTeamTotals struct for OddsTeamTotals
type OddsTeamTotals struct {
	Home *OddsTeamTotal `json:"home,omitempty" xml:"home"`
	Away *OddsTeamTotal `json:"away,omitempty" xml:"away"`
}

// GetHome returns the Home field value if set, zero value otherwise.
func (o *OddsTeamTotals) GetHome() OddsTeamTotal {
	if o == nil || o.Home == nil {
		var ret OddsTeamTotal
		return ret
	}
	return *o.Home
}

// GetHomeOk returns a tuple with the Home field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *OddsTeamTotals) GetHomeOk() (OddsTeamTotal, bool) {
	if o == nil || o.Home == nil {
		var ret OddsTeamTotal
		return ret, false
	}
	return *o.Home, true
}

// HasHome returns a boolean if a field has been set.
func (o *OddsTeamTotals) HasHome() bool {
	if o != nil && o.Home != nil {
		return true
	}

	return false
}

// SetHome gets a reference to the given OddsTeamTotal and assigns it to the Home field.
func (o *OddsTeamTotals) SetHome(v OddsTeamTotal) {
	o.Home = &v
}

// GetAway returns the Away field value if set, zero value otherwise.
func (o *OddsTeamTotals) GetAway() OddsTeamTotal {
	if o == nil || o.Away == nil {
		var ret OddsTeamTotal
		return ret
	}
	return *o.Away
}

// GetAwayOk returns a tuple with the Away field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *OddsTeamTotals) GetAwayOk() (OddsTeamTotal, bool) {
	if o == nil || o.Away == nil {
		var ret OddsTeamTotal
		return ret, false
	}
	return *o.Away, true
}

// HasAway returns a boolean if a field has been set.
func (o *OddsTeamTotals) HasAway() bool {
	if o != nil && o.Away != nil {
		return true
	}

	return false
}

// SetAway gets a reference to the given OddsTeamTotal and assigns it to the Away field.
func (o *OddsTeamTotals) SetAway(v OddsTeamTotal) {
	o.Away = &v
}

type NullableOddsTeamTotals struct {
	Value        OddsTeamTotals
	ExplicitNull bool
}

func (v NullableOddsTeamTotals) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableOddsTeamTotals) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
