/*
 * Pinnacle - Customer API Reference
 *
 *  # Authentication   API uses HTTP Basic access authentication. You need to send Authorization HTTP Request header:    `Authorization: Basic <Base64 value of UTF-8 encoded \"username:password\">`  Example:  `Authorization: Basic U03MyOT23YbzMDc6d3c3O1DQ1` 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pinapi

import (
	"encoding/json"
	"time"
)

// StraightBet struct for StraightBet
type StraightBet struct {
	// Bet identification
	BetId int64 `json:"betId"`
	// Wager identification. All bets placed thru the API will have value 1. Website Classic view supports multiple contest(special) bets placement in the same bet slip in that case the bet would have appropriate wager number, as well as all round robin parlay bets.
	WagerNumber int `json:"wagerNumber"`
	// Date time when the bet was placed.
	PlacedAt time.Time `json:"placedAt"`
	// Bet Status.    ACCEPTED = Bet was accepted,   CANCELLED = Bet is cancelled as per Pinnacle betting rules,   LOSE = The bet is settled as lose,   PENDING_ACCEPTANCE = This status is reserved only for live bets. If a live bet is placed during danger zone or live delay is applied, it will be in PENDING_ACCEPTANCE , otherwise in ACCEPTED status. From this status bet can go to ACCEPTED or NOT_ACCEPTED status,   REFUNDED = When an event is cancelled or when the bet is settled as push, the bet will have REFUNDED status,   NOT_ACCEPTED = Bet was not accepted. Bet can be in this status only if it was previously in PENDING_ACCEPTANCE status,   WON = The bet is settled as won  
	BetStatus string `json:"betStatus"`
	// Bet type.
	BetType string `json:"betType"`
	// Win amount.
	Win float64 `json:"win"`
	// Risk amount.
	Risk float64 `json:"risk"`
	// Win-Loss for settled bets.
	WinLoss NullableFloat64 `json:"winLoss,omitempty"`
	OddsFormat OddsFormat `json:"oddsFormat"`
	// Client’s commission on the bet.
	CustomerCommission NullableFloat64 `json:"customerCommission,omitempty"`
	CancellationReason *CancellationReason `json:"cancellationReason,omitempty"`
	// Update Sequence
	UpdateSequence int64 `json:"updateSequence"`
	SportId *int `json:"sportId,omitempty"`
	LeagueId *int `json:"leagueId,omitempty"`
	EventId *int64 `json:"eventId,omitempty"`
	Handicap NullableFloat64 `json:"handicap,omitempty"`
	Price *float64 `json:"price,omitempty"`
	TeamName *string `json:"teamName,omitempty"`
	// Side type.
	Side NullableString `json:"side,omitempty"`
	// Pitcher name of team1. Only for bets on baseball.
	Pitcher1 NullableString `json:"pitcher1,omitempty"`
	// Pitcher name of team2. Only for bets on baseball.
	Pitcher2 NullableString `json:"pitcher2,omitempty"`
	// Whether the team1 pitcher must start. Only for bets on baseball.
	Pitcher1MustStart NullableString `json:"pitcher1MustStart,omitempty"`
	// Whether the team1 pitcher must start. Only for bets on baseball.
	Pitcher2MustStart NullableString `json:"pitcher2MustStart,omitempty"`
	Team1 *string `json:"team1,omitempty"`
	Team2 *string `json:"team2,omitempty"`
	PeriodNumber *int `json:"periodNumber,omitempty"`
	// Team 1 score that the bet was placed on, only for live bets.
	Team1Score NullableFloat64 `json:"team1Score,omitempty"`
	// Team 2 score that the bet was placed, only for live bets.
	Team2Score NullableFloat64 `json:"team2Score,omitempty"`
	// Full time team 1 score, only for settled bets.
	FtTeam1Score NullableFloat64 `json:"ftTeam1Score,omitempty"`
	// Full time team 2 score, only for settled bets.
	FtTeam2Score NullableFloat64 `json:"ftTeam2Score,omitempty"`
	// .End of period team 1 score, only for settled bets. If the bet was placed on Game period (periodNumber =0) , this will be null . 
	PTeam1Score NullableFloat64 `json:"pTeam1Score,omitempty"`
	// End of period team 2 score, only for settled bets. If the bet was placed on Game period (periodNumber =0), this will be null
	PTeam2Score NullableFloat64 `json:"pTeam2Score,omitempty"`
	// Whether the bet is on live event
	IsLive *string `json:"isLive,omitempty"`
}

// NewStraightBet instantiates a new StraightBet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStraightBet(betId int64, wagerNumber int, placedAt time.Time, betStatus string, betType string, win float64, risk float64, oddsFormat OddsFormat, updateSequence int64, ) *StraightBet {
	this := StraightBet{}
	this.BetId = betId
	this.WagerNumber = wagerNumber
	this.PlacedAt = placedAt
	this.BetStatus = betStatus
	this.BetType = betType
	this.Win = win
	this.Risk = risk
	this.OddsFormat = oddsFormat
	this.UpdateSequence = updateSequence
	return &this
}

// NewStraightBetWithDefaults instantiates a new StraightBet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStraightBetWithDefaults() *StraightBet {
	this := StraightBet{}
	return &this
}

// GetBetId returns the BetId field value
func (o *StraightBet) GetBetId() int64 {
	if o == nil  {
		var ret int64
		return ret
	}

	return o.BetId
}

// GetBetIdOk returns a tuple with the BetId field value
// and a boolean to check if the value has been set.
func (o *StraightBet) GetBetIdOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BetId, true
}

// SetBetId sets field value
func (o *StraightBet) SetBetId(v int64) {
	o.BetId = v
}

// GetWagerNumber returns the WagerNumber field value
func (o *StraightBet) GetWagerNumber() int {
	if o == nil  {
		var ret int
		return ret
	}

	return o.WagerNumber
}

// GetWagerNumberOk returns a tuple with the WagerNumber field value
// and a boolean to check if the value has been set.
func (o *StraightBet) GetWagerNumberOk() (*int, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WagerNumber, true
}

// SetWagerNumber sets field value
func (o *StraightBet) SetWagerNumber(v int) {
	o.WagerNumber = v
}

// GetPlacedAt returns the PlacedAt field value
func (o *StraightBet) GetPlacedAt() time.Time {
	if o == nil  {
		var ret time.Time
		return ret
	}

	return o.PlacedAt
}

// GetPlacedAtOk returns a tuple with the PlacedAt field value
// and a boolean to check if the value has been set.
func (o *StraightBet) GetPlacedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PlacedAt, true
}

// SetPlacedAt sets field value
func (o *StraightBet) SetPlacedAt(v time.Time) {
	o.PlacedAt = v
}

// GetBetStatus returns the BetStatus field value
func (o *StraightBet) GetBetStatus() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.BetStatus
}

// GetBetStatusOk returns a tuple with the BetStatus field value
// and a boolean to check if the value has been set.
func (o *StraightBet) GetBetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BetStatus, true
}

// SetBetStatus sets field value
func (o *StraightBet) SetBetStatus(v string) {
	o.BetStatus = v
}

// GetBetType returns the BetType field value
func (o *StraightBet) GetBetType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.BetType
}

// GetBetTypeOk returns a tuple with the BetType field value
// and a boolean to check if the value has been set.
func (o *StraightBet) GetBetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BetType, true
}

// SetBetType sets field value
func (o *StraightBet) SetBetType(v string) {
	o.BetType = v
}

// GetWin returns the Win field value
func (o *StraightBet) GetWin() float64 {
	if o == nil  {
		var ret float64
		return ret
	}

	return o.Win
}

// GetWinOk returns a tuple with the Win field value
// and a boolean to check if the value has been set.
func (o *StraightBet) GetWinOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Win, true
}

// SetWin sets field value
func (o *StraightBet) SetWin(v float64) {
	o.Win = v
}

// GetRisk returns the Risk field value
func (o *StraightBet) GetRisk() float64 {
	if o == nil  {
		var ret float64
		return ret
	}

	return o.Risk
}

// GetRiskOk returns a tuple with the Risk field value
// and a boolean to check if the value has been set.
func (o *StraightBet) GetRiskOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Risk, true
}

// SetRisk sets field value
func (o *StraightBet) SetRisk(v float64) {
	o.Risk = v
}

// GetWinLoss returns the WinLoss field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetWinLoss() float64 {
	if o == nil || o.WinLoss.Get() == nil {
		var ret float64
		return ret
	}
	return *o.WinLoss.Get()
}

// GetWinLossOk returns a tuple with the WinLoss field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetWinLossOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.WinLoss.Get(), o.WinLoss.IsSet()
}

// HasWinLoss returns a boolean if a field has been set.
func (o *StraightBet) HasWinLoss() bool {
	if o != nil && o.WinLoss.IsSet() {
		return true
	}

	return false
}

// SetWinLoss gets a reference to the given NullableFloat64 and assigns it to the WinLoss field.
func (o *StraightBet) SetWinLoss(v float64) {
	o.WinLoss.Set(&v)
}
// SetWinLossNil sets the value for WinLoss to be an explicit nil
func (o *StraightBet) SetWinLossNil() {
	o.WinLoss.Set(nil)
}

// UnsetWinLoss ensures that no value is present for WinLoss, not even an explicit nil
func (o *StraightBet) UnsetWinLoss() {
	o.WinLoss.Unset()
}

// GetOddsFormat returns the OddsFormat field value
func (o *StraightBet) GetOddsFormat() OddsFormat {
	if o == nil  {
		var ret OddsFormat
		return ret
	}

	return o.OddsFormat
}

// GetOddsFormatOk returns a tuple with the OddsFormat field value
// and a boolean to check if the value has been set.
func (o *StraightBet) GetOddsFormatOk() (*OddsFormat, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OddsFormat, true
}

// SetOddsFormat sets field value
func (o *StraightBet) SetOddsFormat(v OddsFormat) {
	o.OddsFormat = v
}

// GetCustomerCommission returns the CustomerCommission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetCustomerCommission() float64 {
	if o == nil || o.CustomerCommission.Get() == nil {
		var ret float64
		return ret
	}
	return *o.CustomerCommission.Get()
}

// GetCustomerCommissionOk returns a tuple with the CustomerCommission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetCustomerCommissionOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CustomerCommission.Get(), o.CustomerCommission.IsSet()
}

// HasCustomerCommission returns a boolean if a field has been set.
func (o *StraightBet) HasCustomerCommission() bool {
	if o != nil && o.CustomerCommission.IsSet() {
		return true
	}

	return false
}

// SetCustomerCommission gets a reference to the given NullableFloat64 and assigns it to the CustomerCommission field.
func (o *StraightBet) SetCustomerCommission(v float64) {
	o.CustomerCommission.Set(&v)
}
// SetCustomerCommissionNil sets the value for CustomerCommission to be an explicit nil
func (o *StraightBet) SetCustomerCommissionNil() {
	o.CustomerCommission.Set(nil)
}

// UnsetCustomerCommission ensures that no value is present for CustomerCommission, not even an explicit nil
func (o *StraightBet) UnsetCustomerCommission() {
	o.CustomerCommission.Unset()
}

// GetCancellationReason returns the CancellationReason field value if set, zero value otherwise.
func (o *StraightBet) GetCancellationReason() CancellationReason {
	if o == nil || o.CancellationReason == nil {
		var ret CancellationReason
		return ret
	}
	return *o.CancellationReason
}

// GetCancellationReasonOk returns a tuple with the CancellationReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetCancellationReasonOk() (*CancellationReason, bool) {
	if o == nil || o.CancellationReason == nil {
		return nil, false
	}
	return o.CancellationReason, true
}

// HasCancellationReason returns a boolean if a field has been set.
func (o *StraightBet) HasCancellationReason() bool {
	if o != nil && o.CancellationReason != nil {
		return true
	}

	return false
}

// SetCancellationReason gets a reference to the given CancellationReason and assigns it to the CancellationReason field.
func (o *StraightBet) SetCancellationReason(v CancellationReason) {
	o.CancellationReason = &v
}

// GetUpdateSequence returns the UpdateSequence field value
func (o *StraightBet) GetUpdateSequence() int64 {
	if o == nil  {
		var ret int64
		return ret
	}

	return o.UpdateSequence
}

// GetUpdateSequenceOk returns a tuple with the UpdateSequence field value
// and a boolean to check if the value has been set.
func (o *StraightBet) GetUpdateSequenceOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UpdateSequence, true
}

// SetUpdateSequence sets field value
func (o *StraightBet) SetUpdateSequence(v int64) {
	o.UpdateSequence = v
}

// GetSportId returns the SportId field value if set, zero value otherwise.
func (o *StraightBet) GetSportId() int {
	if o == nil || o.SportId == nil {
		var ret int
		return ret
	}
	return *o.SportId
}

// GetSportIdOk returns a tuple with the SportId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetSportIdOk() (*int, bool) {
	if o == nil || o.SportId == nil {
		return nil, false
	}
	return o.SportId, true
}

// HasSportId returns a boolean if a field has been set.
func (o *StraightBet) HasSportId() bool {
	if o != nil && o.SportId != nil {
		return true
	}

	return false
}

// SetSportId gets a reference to the given int and assigns it to the SportId field.
func (o *StraightBet) SetSportId(v int) {
	o.SportId = &v
}

// GetLeagueId returns the LeagueId field value if set, zero value otherwise.
func (o *StraightBet) GetLeagueId() int {
	if o == nil || o.LeagueId == nil {
		var ret int
		return ret
	}
	return *o.LeagueId
}

// GetLeagueIdOk returns a tuple with the LeagueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetLeagueIdOk() (*int, bool) {
	if o == nil || o.LeagueId == nil {
		return nil, false
	}
	return o.LeagueId, true
}

// HasLeagueId returns a boolean if a field has been set.
func (o *StraightBet) HasLeagueId() bool {
	if o != nil && o.LeagueId != nil {
		return true
	}

	return false
}

// SetLeagueId gets a reference to the given int and assigns it to the LeagueId field.
func (o *StraightBet) SetLeagueId(v int) {
	o.LeagueId = &v
}

// GetEventId returns the EventId field value if set, zero value otherwise.
func (o *StraightBet) GetEventId() int64 {
	if o == nil || o.EventId == nil {
		var ret int64
		return ret
	}
	return *o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetEventIdOk() (*int64, bool) {
	if o == nil || o.EventId == nil {
		return nil, false
	}
	return o.EventId, true
}

// HasEventId returns a boolean if a field has been set.
func (o *StraightBet) HasEventId() bool {
	if o != nil && o.EventId != nil {
		return true
	}

	return false
}

// SetEventId gets a reference to the given int64 and assigns it to the EventId field.
func (o *StraightBet) SetEventId(v int64) {
	o.EventId = &v
}

// GetHandicap returns the Handicap field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetHandicap() float64 {
	if o == nil || o.Handicap.Get() == nil {
		var ret float64
		return ret
	}
	return *o.Handicap.Get()
}

// GetHandicapOk returns a tuple with the Handicap field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetHandicapOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Handicap.Get(), o.Handicap.IsSet()
}

// HasHandicap returns a boolean if a field has been set.
func (o *StraightBet) HasHandicap() bool {
	if o != nil && o.Handicap.IsSet() {
		return true
	}

	return false
}

// SetHandicap gets a reference to the given NullableFloat64 and assigns it to the Handicap field.
func (o *StraightBet) SetHandicap(v float64) {
	o.Handicap.Set(&v)
}
// SetHandicapNil sets the value for Handicap to be an explicit nil
func (o *StraightBet) SetHandicapNil() {
	o.Handicap.Set(nil)
}

// UnsetHandicap ensures that no value is present for Handicap, not even an explicit nil
func (o *StraightBet) UnsetHandicap() {
	o.Handicap.Unset()
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *StraightBet) GetPrice() float64 {
	if o == nil || o.Price == nil {
		var ret float64
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetPriceOk() (*float64, bool) {
	if o == nil || o.Price == nil {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *StraightBet) HasPrice() bool {
	if o != nil && o.Price != nil {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float64 and assigns it to the Price field.
func (o *StraightBet) SetPrice(v float64) {
	o.Price = &v
}

// GetTeamName returns the TeamName field value if set, zero value otherwise.
func (o *StraightBet) GetTeamName() string {
	if o == nil || o.TeamName == nil {
		var ret string
		return ret
	}
	return *o.TeamName
}

// GetTeamNameOk returns a tuple with the TeamName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetTeamNameOk() (*string, bool) {
	if o == nil || o.TeamName == nil {
		return nil, false
	}
	return o.TeamName, true
}

// HasTeamName returns a boolean if a field has been set.
func (o *StraightBet) HasTeamName() bool {
	if o != nil && o.TeamName != nil {
		return true
	}

	return false
}

// SetTeamName gets a reference to the given string and assigns it to the TeamName field.
func (o *StraightBet) SetTeamName(v string) {
	o.TeamName = &v
}

// GetSide returns the Side field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetSide() string {
	if o == nil || o.Side.Get() == nil {
		var ret string
		return ret
	}
	return *o.Side.Get()
}

// GetSideOk returns a tuple with the Side field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetSideOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Side.Get(), o.Side.IsSet()
}

// HasSide returns a boolean if a field has been set.
func (o *StraightBet) HasSide() bool {
	if o != nil && o.Side.IsSet() {
		return true
	}

	return false
}

// SetSide gets a reference to the given NullableString and assigns it to the Side field.
func (o *StraightBet) SetSide(v string) {
	o.Side.Set(&v)
}
// SetSideNil sets the value for Side to be an explicit nil
func (o *StraightBet) SetSideNil() {
	o.Side.Set(nil)
}

// UnsetSide ensures that no value is present for Side, not even an explicit nil
func (o *StraightBet) UnsetSide() {
	o.Side.Unset()
}

// GetPitcher1 returns the Pitcher1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetPitcher1() string {
	if o == nil || o.Pitcher1.Get() == nil {
		var ret string
		return ret
	}
	return *o.Pitcher1.Get()
}

// GetPitcher1Ok returns a tuple with the Pitcher1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetPitcher1Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Pitcher1.Get(), o.Pitcher1.IsSet()
}

// HasPitcher1 returns a boolean if a field has been set.
func (o *StraightBet) HasPitcher1() bool {
	if o != nil && o.Pitcher1.IsSet() {
		return true
	}

	return false
}

// SetPitcher1 gets a reference to the given NullableString and assigns it to the Pitcher1 field.
func (o *StraightBet) SetPitcher1(v string) {
	o.Pitcher1.Set(&v)
}
// SetPitcher1Nil sets the value for Pitcher1 to be an explicit nil
func (o *StraightBet) SetPitcher1Nil() {
	o.Pitcher1.Set(nil)
}

// UnsetPitcher1 ensures that no value is present for Pitcher1, not even an explicit nil
func (o *StraightBet) UnsetPitcher1() {
	o.Pitcher1.Unset()
}

// GetPitcher2 returns the Pitcher2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetPitcher2() string {
	if o == nil || o.Pitcher2.Get() == nil {
		var ret string
		return ret
	}
	return *o.Pitcher2.Get()
}

// GetPitcher2Ok returns a tuple with the Pitcher2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetPitcher2Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Pitcher2.Get(), o.Pitcher2.IsSet()
}

// HasPitcher2 returns a boolean if a field has been set.
func (o *StraightBet) HasPitcher2() bool {
	if o != nil && o.Pitcher2.IsSet() {
		return true
	}

	return false
}

// SetPitcher2 gets a reference to the given NullableString and assigns it to the Pitcher2 field.
func (o *StraightBet) SetPitcher2(v string) {
	o.Pitcher2.Set(&v)
}
// SetPitcher2Nil sets the value for Pitcher2 to be an explicit nil
func (o *StraightBet) SetPitcher2Nil() {
	o.Pitcher2.Set(nil)
}

// UnsetPitcher2 ensures that no value is present for Pitcher2, not even an explicit nil
func (o *StraightBet) UnsetPitcher2() {
	o.Pitcher2.Unset()
}

// GetPitcher1MustStart returns the Pitcher1MustStart field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetPitcher1MustStart() string {
	if o == nil || o.Pitcher1MustStart.Get() == nil {
		var ret string
		return ret
	}
	return *o.Pitcher1MustStart.Get()
}

// GetPitcher1MustStartOk returns a tuple with the Pitcher1MustStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetPitcher1MustStartOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Pitcher1MustStart.Get(), o.Pitcher1MustStart.IsSet()
}

// HasPitcher1MustStart returns a boolean if a field has been set.
func (o *StraightBet) HasPitcher1MustStart() bool {
	if o != nil && o.Pitcher1MustStart.IsSet() {
		return true
	}

	return false
}

// SetPitcher1MustStart gets a reference to the given NullableString and assigns it to the Pitcher1MustStart field.
func (o *StraightBet) SetPitcher1MustStart(v string) {
	o.Pitcher1MustStart.Set(&v)
}
// SetPitcher1MustStartNil sets the value for Pitcher1MustStart to be an explicit nil
func (o *StraightBet) SetPitcher1MustStartNil() {
	o.Pitcher1MustStart.Set(nil)
}

// UnsetPitcher1MustStart ensures that no value is present for Pitcher1MustStart, not even an explicit nil
func (o *StraightBet) UnsetPitcher1MustStart() {
	o.Pitcher1MustStart.Unset()
}

// GetPitcher2MustStart returns the Pitcher2MustStart field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetPitcher2MustStart() string {
	if o == nil || o.Pitcher2MustStart.Get() == nil {
		var ret string
		return ret
	}
	return *o.Pitcher2MustStart.Get()
}

// GetPitcher2MustStartOk returns a tuple with the Pitcher2MustStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetPitcher2MustStartOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Pitcher2MustStart.Get(), o.Pitcher2MustStart.IsSet()
}

// HasPitcher2MustStart returns a boolean if a field has been set.
func (o *StraightBet) HasPitcher2MustStart() bool {
	if o != nil && o.Pitcher2MustStart.IsSet() {
		return true
	}

	return false
}

// SetPitcher2MustStart gets a reference to the given NullableString and assigns it to the Pitcher2MustStart field.
func (o *StraightBet) SetPitcher2MustStart(v string) {
	o.Pitcher2MustStart.Set(&v)
}
// SetPitcher2MustStartNil sets the value for Pitcher2MustStart to be an explicit nil
func (o *StraightBet) SetPitcher2MustStartNil() {
	o.Pitcher2MustStart.Set(nil)
}

// UnsetPitcher2MustStart ensures that no value is present for Pitcher2MustStart, not even an explicit nil
func (o *StraightBet) UnsetPitcher2MustStart() {
	o.Pitcher2MustStart.Unset()
}

// GetTeam1 returns the Team1 field value if set, zero value otherwise.
func (o *StraightBet) GetTeam1() string {
	if o == nil || o.Team1 == nil {
		var ret string
		return ret
	}
	return *o.Team1
}

// GetTeam1Ok returns a tuple with the Team1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetTeam1Ok() (*string, bool) {
	if o == nil || o.Team1 == nil {
		return nil, false
	}
	return o.Team1, true
}

// HasTeam1 returns a boolean if a field has been set.
func (o *StraightBet) HasTeam1() bool {
	if o != nil && o.Team1 != nil {
		return true
	}

	return false
}

// SetTeam1 gets a reference to the given string and assigns it to the Team1 field.
func (o *StraightBet) SetTeam1(v string) {
	o.Team1 = &v
}

// GetTeam2 returns the Team2 field value if set, zero value otherwise.
func (o *StraightBet) GetTeam2() string {
	if o == nil || o.Team2 == nil {
		var ret string
		return ret
	}
	return *o.Team2
}

// GetTeam2Ok returns a tuple with the Team2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetTeam2Ok() (*string, bool) {
	if o == nil || o.Team2 == nil {
		return nil, false
	}
	return o.Team2, true
}

// HasTeam2 returns a boolean if a field has been set.
func (o *StraightBet) HasTeam2() bool {
	if o != nil && o.Team2 != nil {
		return true
	}

	return false
}

// SetTeam2 gets a reference to the given string and assigns it to the Team2 field.
func (o *StraightBet) SetTeam2(v string) {
	o.Team2 = &v
}

// GetPeriodNumber returns the PeriodNumber field value if set, zero value otherwise.
func (o *StraightBet) GetPeriodNumber() int {
	if o == nil || o.PeriodNumber == nil {
		var ret int
		return ret
	}
	return *o.PeriodNumber
}

// GetPeriodNumberOk returns a tuple with the PeriodNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetPeriodNumberOk() (*int, bool) {
	if o == nil || o.PeriodNumber == nil {
		return nil, false
	}
	return o.PeriodNumber, true
}

// HasPeriodNumber returns a boolean if a field has been set.
func (o *StraightBet) HasPeriodNumber() bool {
	if o != nil && o.PeriodNumber != nil {
		return true
	}

	return false
}

// SetPeriodNumber gets a reference to the given int and assigns it to the PeriodNumber field.
func (o *StraightBet) SetPeriodNumber(v int) {
	o.PeriodNumber = &v
}

// GetTeam1Score returns the Team1Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetTeam1Score() float64 {
	if o == nil || o.Team1Score.Get() == nil {
		var ret float64
		return ret
	}
	return *o.Team1Score.Get()
}

// GetTeam1ScoreOk returns a tuple with the Team1Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetTeam1ScoreOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Team1Score.Get(), o.Team1Score.IsSet()
}

// HasTeam1Score returns a boolean if a field has been set.
func (o *StraightBet) HasTeam1Score() bool {
	if o != nil && o.Team1Score.IsSet() {
		return true
	}

	return false
}

// SetTeam1Score gets a reference to the given NullableFloat64 and assigns it to the Team1Score field.
func (o *StraightBet) SetTeam1Score(v float64) {
	o.Team1Score.Set(&v)
}
// SetTeam1ScoreNil sets the value for Team1Score to be an explicit nil
func (o *StraightBet) SetTeam1ScoreNil() {
	o.Team1Score.Set(nil)
}

// UnsetTeam1Score ensures that no value is present for Team1Score, not even an explicit nil
func (o *StraightBet) UnsetTeam1Score() {
	o.Team1Score.Unset()
}

// GetTeam2Score returns the Team2Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetTeam2Score() float64 {
	if o == nil || o.Team2Score.Get() == nil {
		var ret float64
		return ret
	}
	return *o.Team2Score.Get()
}

// GetTeam2ScoreOk returns a tuple with the Team2Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetTeam2ScoreOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Team2Score.Get(), o.Team2Score.IsSet()
}

// HasTeam2Score returns a boolean if a field has been set.
func (o *StraightBet) HasTeam2Score() bool {
	if o != nil && o.Team2Score.IsSet() {
		return true
	}

	return false
}

// SetTeam2Score gets a reference to the given NullableFloat64 and assigns it to the Team2Score field.
func (o *StraightBet) SetTeam2Score(v float64) {
	o.Team2Score.Set(&v)
}
// SetTeam2ScoreNil sets the value for Team2Score to be an explicit nil
func (o *StraightBet) SetTeam2ScoreNil() {
	o.Team2Score.Set(nil)
}

// UnsetTeam2Score ensures that no value is present for Team2Score, not even an explicit nil
func (o *StraightBet) UnsetTeam2Score() {
	o.Team2Score.Unset()
}

// GetFtTeam1Score returns the FtTeam1Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetFtTeam1Score() float64 {
	if o == nil || o.FtTeam1Score.Get() == nil {
		var ret float64
		return ret
	}
	return *o.FtTeam1Score.Get()
}

// GetFtTeam1ScoreOk returns a tuple with the FtTeam1Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetFtTeam1ScoreOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.FtTeam1Score.Get(), o.FtTeam1Score.IsSet()
}

// HasFtTeam1Score returns a boolean if a field has been set.
func (o *StraightBet) HasFtTeam1Score() bool {
	if o != nil && o.FtTeam1Score.IsSet() {
		return true
	}

	return false
}

// SetFtTeam1Score gets a reference to the given NullableFloat64 and assigns it to the FtTeam1Score field.
func (o *StraightBet) SetFtTeam1Score(v float64) {
	o.FtTeam1Score.Set(&v)
}
// SetFtTeam1ScoreNil sets the value for FtTeam1Score to be an explicit nil
func (o *StraightBet) SetFtTeam1ScoreNil() {
	o.FtTeam1Score.Set(nil)
}

// UnsetFtTeam1Score ensures that no value is present for FtTeam1Score, not even an explicit nil
func (o *StraightBet) UnsetFtTeam1Score() {
	o.FtTeam1Score.Unset()
}

// GetFtTeam2Score returns the FtTeam2Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetFtTeam2Score() float64 {
	if o == nil || o.FtTeam2Score.Get() == nil {
		var ret float64
		return ret
	}
	return *o.FtTeam2Score.Get()
}

// GetFtTeam2ScoreOk returns a tuple with the FtTeam2Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetFtTeam2ScoreOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.FtTeam2Score.Get(), o.FtTeam2Score.IsSet()
}

// HasFtTeam2Score returns a boolean if a field has been set.
func (o *StraightBet) HasFtTeam2Score() bool {
	if o != nil && o.FtTeam2Score.IsSet() {
		return true
	}

	return false
}

// SetFtTeam2Score gets a reference to the given NullableFloat64 and assigns it to the FtTeam2Score field.
func (o *StraightBet) SetFtTeam2Score(v float64) {
	o.FtTeam2Score.Set(&v)
}
// SetFtTeam2ScoreNil sets the value for FtTeam2Score to be an explicit nil
func (o *StraightBet) SetFtTeam2ScoreNil() {
	o.FtTeam2Score.Set(nil)
}

// UnsetFtTeam2Score ensures that no value is present for FtTeam2Score, not even an explicit nil
func (o *StraightBet) UnsetFtTeam2Score() {
	o.FtTeam2Score.Unset()
}

// GetPTeam1Score returns the PTeam1Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetPTeam1Score() float64 {
	if o == nil || o.PTeam1Score.Get() == nil {
		var ret float64
		return ret
	}
	return *o.PTeam1Score.Get()
}

// GetPTeam1ScoreOk returns a tuple with the PTeam1Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetPTeam1ScoreOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PTeam1Score.Get(), o.PTeam1Score.IsSet()
}

// HasPTeam1Score returns a boolean if a field has been set.
func (o *StraightBet) HasPTeam1Score() bool {
	if o != nil && o.PTeam1Score.IsSet() {
		return true
	}

	return false
}

// SetPTeam1Score gets a reference to the given NullableFloat64 and assigns it to the PTeam1Score field.
func (o *StraightBet) SetPTeam1Score(v float64) {
	o.PTeam1Score.Set(&v)
}
// SetPTeam1ScoreNil sets the value for PTeam1Score to be an explicit nil
func (o *StraightBet) SetPTeam1ScoreNil() {
	o.PTeam1Score.Set(nil)
}

// UnsetPTeam1Score ensures that no value is present for PTeam1Score, not even an explicit nil
func (o *StraightBet) UnsetPTeam1Score() {
	o.PTeam1Score.Unset()
}

// GetPTeam2Score returns the PTeam2Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StraightBet) GetPTeam2Score() float64 {
	if o == nil || o.PTeam2Score.Get() == nil {
		var ret float64
		return ret
	}
	return *o.PTeam2Score.Get()
}

// GetPTeam2ScoreOk returns a tuple with the PTeam2Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StraightBet) GetPTeam2ScoreOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PTeam2Score.Get(), o.PTeam2Score.IsSet()
}

// HasPTeam2Score returns a boolean if a field has been set.
func (o *StraightBet) HasPTeam2Score() bool {
	if o != nil && o.PTeam2Score.IsSet() {
		return true
	}

	return false
}

// SetPTeam2Score gets a reference to the given NullableFloat64 and assigns it to the PTeam2Score field.
func (o *StraightBet) SetPTeam2Score(v float64) {
	o.PTeam2Score.Set(&v)
}
// SetPTeam2ScoreNil sets the value for PTeam2Score to be an explicit nil
func (o *StraightBet) SetPTeam2ScoreNil() {
	o.PTeam2Score.Set(nil)
}

// UnsetPTeam2Score ensures that no value is present for PTeam2Score, not even an explicit nil
func (o *StraightBet) UnsetPTeam2Score() {
	o.PTeam2Score.Unset()
}

// GetIsLive returns the IsLive field value if set, zero value otherwise.
func (o *StraightBet) GetIsLive() string {
	if o == nil || o.IsLive == nil {
		var ret string
		return ret
	}
	return *o.IsLive
}

// GetIsLiveOk returns a tuple with the IsLive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StraightBet) GetIsLiveOk() (*string, bool) {
	if o == nil || o.IsLive == nil {
		return nil, false
	}
	return o.IsLive, true
}

// HasIsLive returns a boolean if a field has been set.
func (o *StraightBet) HasIsLive() bool {
	if o != nil && o.IsLive != nil {
		return true
	}

	return false
}

// SetIsLive gets a reference to the given string and assigns it to the IsLive field.
func (o *StraightBet) SetIsLive(v string) {
	o.IsLive = &v
}

func (o StraightBet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["betId"] = o.BetId
	}
	if true {
		toSerialize["wagerNumber"] = o.WagerNumber
	}
	if true {
		toSerialize["placedAt"] = o.PlacedAt
	}
	if true {
		toSerialize["betStatus"] = o.BetStatus
	}
	if true {
		toSerialize["betType"] = o.BetType
	}
	if true {
		toSerialize["win"] = o.Win
	}
	if true {
		toSerialize["risk"] = o.Risk
	}
	if o.WinLoss.IsSet() {
		toSerialize["winLoss"] = o.WinLoss.Get()
	}
	if true {
		toSerialize["oddsFormat"] = o.OddsFormat
	}
	if o.CustomerCommission.IsSet() {
		toSerialize["customerCommission"] = o.CustomerCommission.Get()
	}
	if o.CancellationReason != nil {
		toSerialize["cancellationReason"] = o.CancellationReason
	}
	if true {
		toSerialize["updateSequence"] = o.UpdateSequence
	}
	if o.SportId != nil {
		toSerialize["sportId"] = o.SportId
	}
	if o.LeagueId != nil {
		toSerialize["leagueId"] = o.LeagueId
	}
	if o.EventId != nil {
		toSerialize["eventId"] = o.EventId
	}
	if o.Handicap.IsSet() {
		toSerialize["handicap"] = o.Handicap.Get()
	}
	if o.Price != nil {
		toSerialize["price"] = o.Price
	}
	if o.TeamName != nil {
		toSerialize["teamName"] = o.TeamName
	}
	if o.Side.IsSet() {
		toSerialize["side"] = o.Side.Get()
	}
	if o.Pitcher1.IsSet() {
		toSerialize["pitcher1"] = o.Pitcher1.Get()
	}
	if o.Pitcher2.IsSet() {
		toSerialize["pitcher2"] = o.Pitcher2.Get()
	}
	if o.Pitcher1MustStart.IsSet() {
		toSerialize["pitcher1MustStart"] = o.Pitcher1MustStart.Get()
	}
	if o.Pitcher2MustStart.IsSet() {
		toSerialize["pitcher2MustStart"] = o.Pitcher2MustStart.Get()
	}
	if o.Team1 != nil {
		toSerialize["team1"] = o.Team1
	}
	if o.Team2 != nil {
		toSerialize["team2"] = o.Team2
	}
	if o.PeriodNumber != nil {
		toSerialize["periodNumber"] = o.PeriodNumber
	}
	if o.Team1Score.IsSet() {
		toSerialize["team1Score"] = o.Team1Score.Get()
	}
	if o.Team2Score.IsSet() {
		toSerialize["team2Score"] = o.Team2Score.Get()
	}
	if o.FtTeam1Score.IsSet() {
		toSerialize["ftTeam1Score"] = o.FtTeam1Score.Get()
	}
	if o.FtTeam2Score.IsSet() {
		toSerialize["ftTeam2Score"] = o.FtTeam2Score.Get()
	}
	if o.PTeam1Score.IsSet() {
		toSerialize["pTeam1Score"] = o.PTeam1Score.Get()
	}
	if o.PTeam2Score.IsSet() {
		toSerialize["pTeam2Score"] = o.PTeam2Score.Get()
	}
	if o.IsLive != nil {
		toSerialize["isLive"] = o.IsLive
	}
	return json.Marshal(toSerialize)
}

type NullableStraightBet struct {
	value *StraightBet
	isSet bool
}

func (v NullableStraightBet) Get() *StraightBet {
	return v.value
}

func (v *NullableStraightBet) Set(val *StraightBet) {
	v.value = val
	v.isSet = true
}

func (v NullableStraightBet) IsSet() bool {
	return v.isSet
}

func (v *NullableStraightBet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStraightBet(val *StraightBet) *NullableStraightBet {
	return &NullableStraightBet{value: val, isSet: true}
}

func (v NullableStraightBet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStraightBet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
