/*
 * Pinnacle - Customer API Reference
 *
 *  # Authentication   API uses HTTP Basic access authentication. You need to send Authorization HTTP Request header:    `Authorization: Basic <Base64 value of UTF-8 encoded \"username:password\">`  Example:  `Authorization: Basic U03MyOT23YbzMDc6d3c3O1DQ1`
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pinapi

import (
	"bytes"
	"encoding/json"
)

// LinesErrorResponse struct for LinesErrorResponse
type LinesErrorResponse struct {
	Status *string        `json:"status,omitempty" xml:"status"`
	Error  *ErrorResponse `json:"error,omitempty" xml:"error"`
	// Code identifying an error that occurred.
	Code *int32 `json:"code,omitempty" xml:"code"`
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *LinesErrorResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *LinesErrorResponse) GetStatusOk() (string, bool) {
	if o == nil || o.Status == nil {
		var ret string
		return ret, false
	}
	return *o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *LinesErrorResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *LinesErrorResponse) SetStatus(v string) {
	o.Status = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *LinesErrorResponse) GetError() ErrorResponse {
	if o == nil || o.Error == nil {
		var ret ErrorResponse
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *LinesErrorResponse) GetErrorOk() (ErrorResponse, bool) {
	if o == nil || o.Error == nil {
		var ret ErrorResponse
		return ret, false
	}
	return *o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *LinesErrorResponse) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given ErrorResponse and assigns it to the Error field.
func (o *LinesErrorResponse) SetError(v ErrorResponse) {
	o.Error = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *LinesErrorResponse) GetCode() int32 {
	if o == nil || o.Code == nil {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *LinesErrorResponse) GetCodeOk() (int32, bool) {
	if o == nil || o.Code == nil {
		var ret int32
		return ret, false
	}
	return *o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *LinesErrorResponse) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *LinesErrorResponse) SetCode(v int32) {
	o.Code = &v
}

type NullableLinesErrorResponse struct {
	Value        LinesErrorResponse
	ExplicitNull bool
}

func (v NullableLinesErrorResponse) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableLinesErrorResponse) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
