/*
 * Pinnacle - Customer API Reference
 *
 *  # Authentication   API uses HTTP Basic access authentication. You need to send Authorization HTTP Request header:    `Authorization: Basic <Base64 value of UTF-8 encoded \"username:password\">`  Example:  `Authorization: Basic U03MyOT23YbzMDc6d3c3O1DQ1`
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pinapi_old

import (
	"bytes"
	"encoding/json"
)

// CancellationReasonResponse Cancellation Response Data
type CancellationReasonResponse struct {
	// Contains a list of Cancellation Reasons.
	CancellationReasons *[]CancellationReason `json:"cancellationReasons,omitempty" xml:"cancellationReasons"`
}

// GetCancellationReasons returns the CancellationReasons field value if set, zero value otherwise.
func (o *CancellationReasonResponse) GetCancellationReasons() []CancellationReason {
	if o == nil || o.CancellationReasons == nil {
		var ret []CancellationReason
		return ret
	}
	return *o.CancellationReasons
}

// GetCancellationReasonsOk returns a tuple with the CancellationReasons field value if set, zero value otherwise
// and a boolean to check if the value has been set.
func (o *CancellationReasonResponse) GetCancellationReasonsOk() ([]CancellationReason, bool) {
	if o == nil || o.CancellationReasons == nil {
		var ret []CancellationReason
		return ret, false
	}
	return *o.CancellationReasons, true
}

// HasCancellationReasons returns a boolean if a field has been set.
func (o *CancellationReasonResponse) HasCancellationReasons() bool {
	if o != nil && o.CancellationReasons != nil {
		return true
	}

	return false
}

// SetCancellationReasons gets a reference to the given []CancellationReason and assigns it to the CancellationReasons field.
func (o *CancellationReasonResponse) SetCancellationReasons(v []CancellationReason) {
	o.CancellationReasons = &v
}

type NullableCancellationReasonResponse struct {
	Value        CancellationReasonResponse
	ExplicitNull bool
}

func (v NullableCancellationReasonResponse) MarshalJSON() ([]byte, error) {
	switch {
	case v.ExplicitNull:
		return []byte("null"), nil
	default:
		return json.Marshal(v.Value)
	}
}

func (v *NullableCancellationReasonResponse) UnmarshalJSON(src []byte) error {
	if bytes.Equal(src, []byte("null")) {
		v.ExplicitNull = true
		return nil
	}

	return json.Unmarshal(src, &v.Value)
}
