/*
 * Black API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package blackapi

import (
	"encoding/json"
)

// LoginRequest struct for LoginRequest
type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Full bool `json:"full"`
	Lang string `json:"lang"`
}

// NewLoginRequest instantiates a new LoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginRequest(username string, password string, full bool, lang string, ) *LoginRequest {
	this := LoginRequest{}
	this.Username = username
	this.Password = password
	this.Full = full
	this.Lang = lang
	return &this
}

// NewLoginRequestWithDefaults instantiates a new LoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginRequestWithDefaults() *LoginRequest {
	this := LoginRequest{}
	var full bool = true
	this.Full = full
	var lang string = "en"
	this.Lang = lang
	return &this
}

// GetUsername returns the Username field value
func (o *LoginRequest) GetUsername() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *LoginRequest) GetUsernameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *LoginRequest) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *LoginRequest) GetPassword() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginRequest) GetPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginRequest) SetPassword(v string) {
	o.Password = v
}

// GetFull returns the Full field value
func (o *LoginRequest) GetFull() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.Full
}

// GetFullOk returns a tuple with the Full field value
// and a boolean to check if the value has been set.
func (o *LoginRequest) GetFullOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Full, true
}

// SetFull sets field value
func (o *LoginRequest) SetFull(v bool) {
	o.Full = v
}

// GetLang returns the Lang field value
func (o *LoginRequest) GetLang() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Lang
}

// GetLangOk returns a tuple with the Lang field value
// and a boolean to check if the value has been set.
func (o *LoginRequest) GetLangOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Lang, true
}

// SetLang sets field value
func (o *LoginRequest) SetLang(v string) {
	o.Lang = v
}

func (o LoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["username"] = o.Username
	}
	if true {
		toSerialize["password"] = o.Password
	}
	if true {
		toSerialize["full"] = o.Full
	}
	if true {
		toSerialize["lang"] = o.Lang
	}
	return json.Marshal(toSerialize)
}

type NullableLoginRequest struct {
	value *LoginRequest
	isSet bool
}

func (v NullableLoginRequest) Get() *LoginRequest {
	return v.value
}

func (v *NullableLoginRequest) Set(val *LoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginRequest(val *LoginRequest) *NullableLoginRequest {
	return &NullableLoginRequest{value: val, isSet: true}
}

func (v NullableLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
