swagger: '2.0'
info:
  version: 1.0.0
  title: Pinnacle - Customer API Reference
  description:  |
    Удалил /v1/translations, вроде как перевод на другие языки
host: api.pinnacle.com
schemes:
  - https
security:
  - basicAuth: []
paths:
  /v1/client/balance:
    get:
      summary: Get Client Balance - v1
      description: Returns current client balance.
      operationId: Client_Balance_V1_Get
      consumes: []
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ClientBalanceResponse'
        '400':
          description: BadRequest
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: InternalServerError
          schema:
            $ref: '#/definitions/ExtendedErrorResponse'
      deprecated: false
securityDefinitions:
  basicAuth:
    type: basic
definitions:
  ErrorResponse:
    type: object
    properties:
      code:
        type: string
        description: Identifier representing the type of error that occurred.
      message:
        type: string
        description: Description of the error.
    description: Contains details of an error that was encountered.
  ExtendedErrorResponse:
    type: object
    properties:
      ref:
        type: string
      code:
        type: string
      message:
        type: string
  ClientBalanceResponse:
    description: Client Balance Details
    type: object
    properties:
      availableBalance:
        format: double
        description: Amount available for betting.
        type: number
      outstandingTransactions:
        format: double
        description: Sum of not yet settled bet amounts.
        type: number
      givenCredit:
        format: double
        description: Client’s credit.
        type: number
      currency:
        description: Client’s currency code.
        type: string
    required: 
      - availableBalance
      - outstandingTransactions
      - givenCredit
      - currency
  TranslationResponse:
    type: object
    properties:
      translations:
        type: array
        description: Collection of translations.
        items:
          $ref: '#/definitions/Translation'
  Translation:
    type: object
    properties:
      text:
        type: string
        description: Original requested text to be translated.
        example: Football
      cultures:
        type: array
        description: Collection of translations by culture.
        items:
          $ref: '#/definitions/TranslationByCulture'
  TranslationByCulture:
    type: object
    properties:
      id:
        type: string
        description: Culture based on which the text is translated.
        enum:
          - en-US
          - en-GB
          - zh-CN
          - zh-TW
          - fi-FI
          - de-DE
          - he-IL
          - it-IT
          - nb-NO
          - pt-BR
          - ru-RU
          - es-ES
          - sv-SE
          - th-TH
          - pl-PL
          - fr-FR
          - ja-JP
          - ko-KR
          - vi-VN
          - id-ID
          - cs-CZ
        example: fr-FR
      text:
        type: string
        description: Translation text.
        example: Football américain
