// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: surebet.proto

package surebetpb

import (
	context "context"
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CheckLineRequest struct {
	Side *Side `protobuf:"bytes,1,opt,name=side,proto3" json:"side,omitempty"`
}

func (m *CheckLineRequest) Reset()      { *m = CheckLineRequest{} }
func (*CheckLineRequest) ProtoMessage() {}
func (*CheckLineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4fed42b5e3ea230, []int{0}
}
func (m *CheckLineRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckLineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckLineRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckLineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLineRequest.Merge(m, src)
}
func (m *CheckLineRequest) XXX_Size() int {
	return m.Size()
}
func (m *CheckLineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLineRequest proto.InternalMessageInfo

func (m *CheckLineRequest) GetSide() *Side {
	if m != nil {
		return m.Side
	}
	return nil
}

type CheckLineResponse struct {
	Side *Side `protobuf:"bytes,1,opt,name=side,proto3" json:"side,omitempty"`
}

func (m *CheckLineResponse) Reset()      { *m = CheckLineResponse{} }
func (*CheckLineResponse) ProtoMessage() {}
func (*CheckLineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4fed42b5e3ea230, []int{1}
}
func (m *CheckLineResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckLineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckLineResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckLineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLineResponse.Merge(m, src)
}
func (m *CheckLineResponse) XXX_Size() int {
	return m.Size()
}
func (m *CheckLineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLineResponse proto.InternalMessageInfo

func (m *CheckLineResponse) GetSide() *Side {
	if m != nil {
		return m.Side
	}
	return nil
}

type PingRequest struct {
}

func (m *PingRequest) Reset()      { *m = PingRequest{} }
func (*PingRequest) ProtoMessage() {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4fed42b5e3ea230, []int{2}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return m.Size()
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
}

func (m *PingResponse) Reset()      { *m = PingResponse{} }
func (*PingResponse) ProtoMessage() {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4fed42b5e3ea230, []int{3}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return m.Size()
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type Side struct {
	Num         int64   `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	ServiceName string  `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceId   int64   `protobuf:"varint,15,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	SportName   string  `protobuf:"bytes,3,opt,name=sport_name,json=sportName,proto3" json:"sport_name,omitempty"`
	SportId     int64   `protobuf:"varint,11,opt,name=sport_id,json=sportId,proto3" json:"sport_id,omitempty"`
	LeagueName  string  `protobuf:"bytes,4,opt,name=league_name,json=leagueName,proto3" json:"league_name,omitempty"`
	LeagueId    int64   `protobuf:"varint,12,opt,name=league_id,json=leagueId,proto3" json:"league_id,omitempty"`
	Home        string  `protobuf:"bytes,5,opt,name=home,proto3" json:"home,omitempty"`
	Away        string  `protobuf:"bytes,6,opt,name=away,proto3" json:"away,omitempty"`
	MarketName  string  `protobuf:"bytes,7,opt,name=market_name,json=marketName,proto3" json:"market_name,omitempty"`
	MarketId    int64   `protobuf:"varint,16,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Price       float64 `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	PriceId     int64   `protobuf:"varint,17,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	Url         string  `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	Initiator   bool    `protobuf:"varint,10,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Starts      string  `protobuf:"bytes,13,opt,name=starts,proto3" json:"starts,omitempty"`
	EventId     int64   `protobuf:"varint,14,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (m *Side) Reset()      { *m = Side{} }
func (*Side) ProtoMessage() {}
func (*Side) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4fed42b5e3ea230, []int{4}
}
func (m *Side) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Side) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Side.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Side) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Side.Merge(m, src)
}
func (m *Side) XXX_Size() int {
	return m.Size()
}
func (m *Side) XXX_DiscardUnknown() {
	xxx_messageInfo_Side.DiscardUnknown(m)
}

var xxx_messageInfo_Side proto.InternalMessageInfo

func (m *Side) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Side) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Side) GetServiceId() int64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *Side) GetSportName() string {
	if m != nil {
		return m.SportName
	}
	return ""
}

func (m *Side) GetSportId() int64 {
	if m != nil {
		return m.SportId
	}
	return 0
}

func (m *Side) GetLeagueName() string {
	if m != nil {
		return m.LeagueName
	}
	return ""
}

func (m *Side) GetLeagueId() int64 {
	if m != nil {
		return m.LeagueId
	}
	return 0
}

func (m *Side) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *Side) GetAway() string {
	if m != nil {
		return m.Away
	}
	return ""
}

func (m *Side) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *Side) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *Side) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Side) GetPriceId() int64 {
	if m != nil {
		return m.PriceId
	}
	return 0
}

func (m *Side) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Side) GetInitiator() bool {
	if m != nil {
		return m.Initiator
	}
	return false
}

func (m *Side) GetStarts() string {
	if m != nil {
		return m.Starts
	}
	return ""
}

func (m *Side) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckLineRequest)(nil), "surebetpb.CheckLineRequest")
	proto.RegisterType((*CheckLineResponse)(nil), "surebetpb.CheckLineResponse")
	proto.RegisterType((*PingRequest)(nil), "surebetpb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "surebetpb.PingResponse")
	proto.RegisterType((*Side)(nil), "surebetpb.Side")
}

func init() { proto.RegisterFile("surebet.proto", fileDescriptor_c4fed42b5e3ea230) }

var fileDescriptor_c4fed42b5e3ea230 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xbf, 0x72, 0xd3, 0x40,
	0x10, 0xc6, 0x75, 0x58, 0x89, 0xad, 0x95, 0x9d, 0x38, 0x37, 0x4c, 0x38, 0x9c, 0x70, 0x18, 0xd3,
	0xb8, 0xc1, 0x99, 0x09, 0x45, 0xa0, 0x85, 0x06, 0xcd, 0x30, 0x0c, 0xa3, 0x74, 0x34, 0x8c, 0xe4,
	0x3b, 0xe4, 0x9b, 0x44, 0x7f, 0xd0, 0x9f, 0x30, 0x74, 0x3c, 0x01, 0xc3, 0x63, 0xf0, 0x28, 0x14,
	0x14, 0x29, 0x53, 0x62, 0xf9, 0x05, 0x28, 0x29, 0x99, 0xdb, 0x3b, 0x27, 0x1e, 0xa0, 0xa0, 0xdb,
	0xef, 0xdb, 0xfd, 0xed, 0x27, 0xd9, 0x2b, 0x18, 0x54, 0x4d, 0x29, 0x63, 0x59, 0xcf, 0x8a, 0x32,
	0xaf, 0x73, 0xea, 0x59, 0x59, 0xc4, 0xa3, 0x47, 0x89, 0xaa, 0x17, 0x4d, 0x3c, 0x9b, 0xe7, 0xe9,
	0x51, 0x92, 0x27, 0xf9, 0x11, 0x4e, 0xc4, 0xcd, 0x3b, 0x54, 0x28, 0xb0, 0x32, 0xe4, 0xe4, 0x04,
	0x86, 0xcf, 0x17, 0x72, 0x7e, 0xf6, 0x52, 0x65, 0x32, 0x94, 0xef, 0x1b, 0x59, 0xd5, 0xf4, 0x21,
	0xb8, 0x95, 0x12, 0x92, 0x91, 0x31, 0x99, 0xfa, 0xc7, 0xbb, 0xb3, 0xeb, 0xe5, 0xb3, 0x53, 0x25,
	0x64, 0x88, 0xcd, 0xc9, 0x13, 0xd8, 0xdb, 0x00, 0xab, 0x22, 0xcf, 0x2a, 0xf9, 0x7f, 0xe4, 0x00,
	0xfc, 0xd7, 0x2a, 0x4b, 0x6c, 0xda, 0x64, 0x07, 0xfa, 0x46, 0x9a, 0x1d, 0x93, 0xef, 0x1d, 0x70,
	0xf5, 0x34, 0x1d, 0x42, 0x27, 0x6b, 0x52, 0xdc, 0xd5, 0x09, 0x75, 0x49, 0x1f, 0x40, 0xbf, 0x92,
	0xe5, 0x85, 0x9a, 0xcb, 0xb7, 0x59, 0x94, 0x4a, 0x76, 0x6b, 0x4c, 0xa6, 0x5e, 0xe8, 0x5b, 0xef,
	0x55, 0x94, 0x4a, 0x7a, 0x0f, 0x60, 0x3d, 0xa2, 0x04, 0xdb, 0x45, 0xd6, 0xb3, 0x4e, 0x20, 0xb0,
	0x5d, 0xe4, 0x65, 0x6d, 0xf8, 0x0e, 0xf2, 0x1e, 0x3a, 0x48, 0xdf, 0x85, 0x9e, 0x69, 0x2b, 0xc1,
	0x7c, 0x64, 0xbb, 0xa8, 0x03, 0x41, 0xef, 0x83, 0x7f, 0x2e, 0xa3, 0xa4, 0xb1, 0xd1, 0x2e, 0xa2,
	0x60, 0x2c, 0x64, 0x0f, 0xc0, 0xb3, 0x03, 0x4a, 0xb0, 0x3e, 0xc2, 0x3d, 0x63, 0x04, 0x82, 0x52,
	0x70, 0x17, 0x79, 0x2a, 0xd9, 0x16, 0x62, 0x58, 0x6b, 0x2f, 0xfa, 0x10, 0x7d, 0x64, 0xdb, 0xc6,
	0xd3, 0xb5, 0x4e, 0x49, 0xa3, 0xf2, 0x4c, 0xda, 0x07, 0xec, 0x9a, 0x14, 0x63, 0xad, 0x53, 0xec,
	0x80, 0x12, 0x6c, 0x68, 0x52, 0x8c, 0x11, 0x08, 0x7a, 0x1b, 0xb6, 0x8a, 0x52, 0xcd, 0x25, 0xeb,
	0x8d, 0xc9, 0x94, 0x84, 0x46, 0xe8, 0x97, 0xc2, 0x42, 0x13, 0x7b, 0xe6, 0xa5, 0x50, 0x07, 0x42,
	0xff, 0xc4, 0x4d, 0x79, 0xce, 0x3c, 0x8c, 0xd1, 0x25, 0x3d, 0x04, 0x4f, 0x65, 0xaa, 0x56, 0x51,
	0x9d, 0x97, 0x0c, 0xc6, 0x64, 0xda, 0x0b, 0x6f, 0x0c, 0xba, 0x0f, 0xdb, 0x55, 0x1d, 0x95, 0x75,
	0xc5, 0x06, 0x88, 0x58, 0xa5, 0x23, 0xe4, 0x85, 0xcc, 0xf0, 0xa1, 0x76, 0x4c, 0x04, 0xea, 0x40,
	0x1c, 0x7f, 0x26, 0xd0, 0x3d, 0x35, 0x67, 0x40, 0x9f, 0x82, 0xab, 0xff, 0x6a, 0xba, 0xbf, 0x71,
	0x18, 0x1b, 0xa7, 0x30, 0xba, 0xf3, 0x97, 0x6f, 0x6f, 0xc2, 0xa1, 0x2f, 0xc0, 0xbb, 0x3e, 0x37,
	0x7a, 0xb0, 0x31, 0xf7, 0xe7, 0xf5, 0x8e, 0x0e, 0xff, 0xdd, 0x5c, 0x6f, 0x7a, 0x76, 0x72, 0xb5,
	0xe4, 0xce, 0xcf, 0x25, 0x27, 0xbf, 0x96, 0x9c, 0x7c, 0x6a, 0x39, 0xf9, 0xda, 0x72, 0xf2, 0xad,
	0xe5, 0xe4, 0xb2, 0xe5, 0xe4, 0x47, 0xcb, 0xc9, 0x97, 0x15, 0x77, 0x2e, 0x57, 0xdc, 0xb9, 0x5a,
	0x71, 0xe7, 0xcd, 0xcd, 0x97, 0x15, 0x6f, 0xe3, 0x17, 0xf3, 0xf8, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x82, 0x55, 0xa0, 0x63, 0x7c, 0x03, 0x00, 0x00,
}

func (this *CheckLineRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CheckLineRequest)
	if !ok {
		that2, ok := that.(CheckLineRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Side.Equal(that1.Side) {
		return false
	}
	return true
}
func (this *CheckLineResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CheckLineResponse)
	if !ok {
		that2, ok := that.(CheckLineResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Side.Equal(that1.Side) {
		return false
	}
	return true
}
func (this *PingRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PingRequest)
	if !ok {
		that2, ok := that.(PingRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *PingResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PingResponse)
	if !ok {
		that2, ok := that.(PingResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *Side) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Side)
	if !ok {
		that2, ok := that.(Side)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Num != that1.Num {
		return false
	}
	if this.ServiceName != that1.ServiceName {
		return false
	}
	if this.ServiceId != that1.ServiceId {
		return false
	}
	if this.SportName != that1.SportName {
		return false
	}
	if this.SportId != that1.SportId {
		return false
	}
	if this.LeagueName != that1.LeagueName {
		return false
	}
	if this.LeagueId != that1.LeagueId {
		return false
	}
	if this.Home != that1.Home {
		return false
	}
	if this.Away != that1.Away {
		return false
	}
	if this.MarketName != that1.MarketName {
		return false
	}
	if this.MarketId != that1.MarketId {
		return false
	}
	if this.Price != that1.Price {
		return false
	}
	if this.PriceId != that1.PriceId {
		return false
	}
	if this.Url != that1.Url {
		return false
	}
	if this.Initiator != that1.Initiator {
		return false
	}
	if this.Starts != that1.Starts {
		return false
	}
	if this.EventId != that1.EventId {
		return false
	}
	return true
}
func (this *CheckLineRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&surebetpb.CheckLineRequest{")
	if this.Side != nil {
		s = append(s, "Side: "+fmt.Sprintf("%#v", this.Side)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CheckLineResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&surebetpb.CheckLineResponse{")
	if this.Side != nil {
		s = append(s, "Side: "+fmt.Sprintf("%#v", this.Side)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PingRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&surebetpb.PingRequest{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PingResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&surebetpb.PingResponse{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Side) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 21)
	s = append(s, "&surebetpb.Side{")
	s = append(s, "Num: "+fmt.Sprintf("%#v", this.Num)+",\n")
	s = append(s, "ServiceName: "+fmt.Sprintf("%#v", this.ServiceName)+",\n")
	s = append(s, "ServiceId: "+fmt.Sprintf("%#v", this.ServiceId)+",\n")
	s = append(s, "SportName: "+fmt.Sprintf("%#v", this.SportName)+",\n")
	s = append(s, "SportId: "+fmt.Sprintf("%#v", this.SportId)+",\n")
	s = append(s, "LeagueName: "+fmt.Sprintf("%#v", this.LeagueName)+",\n")
	s = append(s, "LeagueId: "+fmt.Sprintf("%#v", this.LeagueId)+",\n")
	s = append(s, "Home: "+fmt.Sprintf("%#v", this.Home)+",\n")
	s = append(s, "Away: "+fmt.Sprintf("%#v", this.Away)+",\n")
	s = append(s, "MarketName: "+fmt.Sprintf("%#v", this.MarketName)+",\n")
	s = append(s, "MarketId: "+fmt.Sprintf("%#v", this.MarketId)+",\n")
	s = append(s, "Price: "+fmt.Sprintf("%#v", this.Price)+",\n")
	s = append(s, "PriceId: "+fmt.Sprintf("%#v", this.PriceId)+",\n")
	s = append(s, "Url: "+fmt.Sprintf("%#v", this.Url)+",\n")
	s = append(s, "Initiator: "+fmt.Sprintf("%#v", this.Initiator)+",\n")
	s = append(s, "Starts: "+fmt.Sprintf("%#v", this.Starts)+",\n")
	s = append(s, "EventId: "+fmt.Sprintf("%#v", this.EventId)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSurebet(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SurebetClient is the client API for Surebet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SurebetClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	CheckLine(ctx context.Context, in *CheckLineRequest, opts ...grpc.CallOption) (*CheckLineResponse, error)
}

type surebetClient struct {
	cc *grpc.ClientConn
}

func NewSurebetClient(cc *grpc.ClientConn) SurebetClient {
	return &surebetClient{cc}
}

func (c *surebetClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/surebetpb.Surebet/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surebetClient) CheckLine(ctx context.Context, in *CheckLineRequest, opts ...grpc.CallOption) (*CheckLineResponse, error) {
	out := new(CheckLineResponse)
	err := c.cc.Invoke(ctx, "/surebetpb.Surebet/CheckLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SurebetServer is the server API for Surebet service.
type SurebetServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	CheckLine(context.Context, *CheckLineRequest) (*CheckLineResponse, error)
}

// UnimplementedSurebetServer can be embedded to have forward compatible implementations.
type UnimplementedSurebetServer struct {
}

func (*UnimplementedSurebetServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedSurebetServer) CheckLine(ctx context.Context, req *CheckLineRequest) (*CheckLineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLine not implemented")
}

func RegisterSurebetServer(s *grpc.Server, srv SurebetServer) {
	s.RegisterService(&_Surebet_serviceDesc, srv)
}

func _Surebet_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurebetServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surebetpb.Surebet/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurebetServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surebet_CheckLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurebetServer).CheckLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surebetpb.Surebet/CheckLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurebetServer).CheckLine(ctx, req.(*CheckLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Surebet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "surebetpb.Surebet",
	HandlerType: (*SurebetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Surebet_Ping_Handler,
		},
		{
			MethodName: "CheckLine",
			Handler:    _Surebet_CheckLine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "surebet.proto",
}

func (m *CheckLineRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckLineRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckLineRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Side != nil {
		{
			size, err := m.Side.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSurebet(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CheckLineResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckLineResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckLineResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Side != nil {
		{
			size, err := m.Side.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSurebet(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *PingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Side) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Side) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Side) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PriceId != 0 {
		i = encodeVarintSurebet(dAtA, i, uint64(m.PriceId))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.MarketId != 0 {
		i = encodeVarintSurebet(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.ServiceId != 0 {
		i = encodeVarintSurebet(dAtA, i, uint64(m.ServiceId))
		i--
		dAtA[i] = 0x78
	}
	if m.EventId != 0 {
		i = encodeVarintSurebet(dAtA, i, uint64(m.EventId))
		i--
		dAtA[i] = 0x70
	}
	if len(m.Starts) > 0 {
		i -= len(m.Starts)
		copy(dAtA[i:], m.Starts)
		i = encodeVarintSurebet(dAtA, i, uint64(len(m.Starts)))
		i--
		dAtA[i] = 0x6a
	}
	if m.LeagueId != 0 {
		i = encodeVarintSurebet(dAtA, i, uint64(m.LeagueId))
		i--
		dAtA[i] = 0x60
	}
	if m.SportId != 0 {
		i = encodeVarintSurebet(dAtA, i, uint64(m.SportId))
		i--
		dAtA[i] = 0x58
	}
	if m.Initiator {
		i--
		if m.Initiator {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintSurebet(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Price != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Price))))
		i--
		dAtA[i] = 0x41
	}
	if len(m.MarketName) > 0 {
		i -= len(m.MarketName)
		copy(dAtA[i:], m.MarketName)
		i = encodeVarintSurebet(dAtA, i, uint64(len(m.MarketName)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Away) > 0 {
		i -= len(m.Away)
		copy(dAtA[i:], m.Away)
		i = encodeVarintSurebet(dAtA, i, uint64(len(m.Away)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Home) > 0 {
		i -= len(m.Home)
		copy(dAtA[i:], m.Home)
		i = encodeVarintSurebet(dAtA, i, uint64(len(m.Home)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.LeagueName) > 0 {
		i -= len(m.LeagueName)
		copy(dAtA[i:], m.LeagueName)
		i = encodeVarintSurebet(dAtA, i, uint64(len(m.LeagueName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SportName) > 0 {
		i -= len(m.SportName)
		copy(dAtA[i:], m.SportName)
		i = encodeVarintSurebet(dAtA, i, uint64(len(m.SportName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ServiceName) > 0 {
		i -= len(m.ServiceName)
		copy(dAtA[i:], m.ServiceName)
		i = encodeVarintSurebet(dAtA, i, uint64(len(m.ServiceName)))
		i--
		dAtA[i] = 0x12
	}
	if m.Num != 0 {
		i = encodeVarintSurebet(dAtA, i, uint64(m.Num))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSurebet(dAtA []byte, offset int, v uint64) int {
	offset -= sovSurebet(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedCheckLineRequest(r randySurebet, easy bool) *CheckLineRequest {
	this := &CheckLineRequest{}
	if r.Intn(5) != 0 {
		this.Side = NewPopulatedSide(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedCheckLineResponse(r randySurebet, easy bool) *CheckLineResponse {
	this := &CheckLineResponse{}
	if r.Intn(5) != 0 {
		this.Side = NewPopulatedSide(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPingRequest(r randySurebet, easy bool) *PingRequest {
	this := &PingRequest{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPingResponse(r randySurebet, easy bool) *PingResponse {
	this := &PingResponse{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSide(r randySurebet, easy bool) *Side {
	this := &Side{}
	this.Num = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Num *= -1
	}
	this.ServiceName = string(randStringSurebet(r))
	this.SportName = string(randStringSurebet(r))
	this.LeagueName = string(randStringSurebet(r))
	this.Home = string(randStringSurebet(r))
	this.Away = string(randStringSurebet(r))
	this.MarketName = string(randStringSurebet(r))
	this.Price = float64(r.Float64())
	if r.Intn(2) == 0 {
		this.Price *= -1
	}
	this.Url = string(randStringSurebet(r))
	this.Initiator = bool(bool(r.Intn(2) == 0))
	this.SportId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.SportId *= -1
	}
	this.LeagueId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.LeagueId *= -1
	}
	this.Starts = string(randStringSurebet(r))
	this.EventId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.EventId *= -1
	}
	this.ServiceId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.ServiceId *= -1
	}
	this.MarketId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.MarketId *= -1
	}
	this.PriceId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.PriceId *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randySurebet interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneSurebet(r randySurebet) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringSurebet(r randySurebet) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneSurebet(r)
	}
	return string(tmps)
}
func randUnrecognizedSurebet(r randySurebet, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldSurebet(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldSurebet(dAtA []byte, r randySurebet, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateSurebet(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateSurebet(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateSurebet(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateSurebet(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateSurebet(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateSurebet(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateSurebet(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *CheckLineRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Side != nil {
		l = m.Side.Size()
		n += 1 + l + sovSurebet(uint64(l))
	}
	return n
}

func (m *CheckLineResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Side != nil {
		l = m.Side.Size()
		n += 1 + l + sovSurebet(uint64(l))
	}
	return n
}

func (m *PingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *PingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Side) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Num != 0 {
		n += 1 + sovSurebet(uint64(m.Num))
	}
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovSurebet(uint64(l))
	}
	l = len(m.SportName)
	if l > 0 {
		n += 1 + l + sovSurebet(uint64(l))
	}
	l = len(m.LeagueName)
	if l > 0 {
		n += 1 + l + sovSurebet(uint64(l))
	}
	l = len(m.Home)
	if l > 0 {
		n += 1 + l + sovSurebet(uint64(l))
	}
	l = len(m.Away)
	if l > 0 {
		n += 1 + l + sovSurebet(uint64(l))
	}
	l = len(m.MarketName)
	if l > 0 {
		n += 1 + l + sovSurebet(uint64(l))
	}
	if m.Price != 0 {
		n += 9
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovSurebet(uint64(l))
	}
	if m.Initiator {
		n += 2
	}
	if m.SportId != 0 {
		n += 1 + sovSurebet(uint64(m.SportId))
	}
	if m.LeagueId != 0 {
		n += 1 + sovSurebet(uint64(m.LeagueId))
	}
	l = len(m.Starts)
	if l > 0 {
		n += 1 + l + sovSurebet(uint64(l))
	}
	if m.EventId != 0 {
		n += 1 + sovSurebet(uint64(m.EventId))
	}
	if m.ServiceId != 0 {
		n += 1 + sovSurebet(uint64(m.ServiceId))
	}
	if m.MarketId != 0 {
		n += 2 + sovSurebet(uint64(m.MarketId))
	}
	if m.PriceId != 0 {
		n += 2 + sovSurebet(uint64(m.PriceId))
	}
	return n
}

func sovSurebet(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSurebet(x uint64) (n int) {
	return sovSurebet(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CheckLineRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CheckLineRequest{`,
		`Side:` + strings.Replace(this.Side.String(), "Side", "Side", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CheckLineResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CheckLineResponse{`,
		`Side:` + strings.Replace(this.Side.String(), "Side", "Side", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PingRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PingRequest{`,
		`}`,
	}, "")
	return s
}
func (this *PingResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PingResponse{`,
		`}`,
	}, "")
	return s
}
func (this *Side) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Side{`,
		`Num:` + fmt.Sprintf("%v", this.Num) + `,`,
		`ServiceName:` + fmt.Sprintf("%v", this.ServiceName) + `,`,
		`SportName:` + fmt.Sprintf("%v", this.SportName) + `,`,
		`LeagueName:` + fmt.Sprintf("%v", this.LeagueName) + `,`,
		`Home:` + fmt.Sprintf("%v", this.Home) + `,`,
		`Away:` + fmt.Sprintf("%v", this.Away) + `,`,
		`MarketName:` + fmt.Sprintf("%v", this.MarketName) + `,`,
		`Price:` + fmt.Sprintf("%v", this.Price) + `,`,
		`Url:` + fmt.Sprintf("%v", this.Url) + `,`,
		`Initiator:` + fmt.Sprintf("%v", this.Initiator) + `,`,
		`SportId:` + fmt.Sprintf("%v", this.SportId) + `,`,
		`LeagueId:` + fmt.Sprintf("%v", this.LeagueId) + `,`,
		`Starts:` + fmt.Sprintf("%v", this.Starts) + `,`,
		`EventId:` + fmt.Sprintf("%v", this.EventId) + `,`,
		`ServiceId:` + fmt.Sprintf("%v", this.ServiceId) + `,`,
		`MarketId:` + fmt.Sprintf("%v", this.MarketId) + `,`,
		`PriceId:` + fmt.Sprintf("%v", this.PriceId) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringSurebet(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CheckLineRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSurebet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckLineRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckLineRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Side", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Side == nil {
				m.Side = &Side{}
			}
			if err := m.Side.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSurebet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckLineResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSurebet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckLineResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckLineResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Side", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Side == nil {
				m.Side = &Side{}
			}
			if err := m.Side.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSurebet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSurebet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipSurebet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSurebet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipSurebet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Side) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSurebet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Side: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Side: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num", wireType)
			}
			m.Num = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SportName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SportName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeagueName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LeagueName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Home", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Home = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Away", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Away = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Price = float64(math.Float64frombits(v))
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Initiator", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Initiator = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SportId", wireType)
			}
			m.SportId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SportId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeagueId", wireType)
			}
			m.LeagueId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeagueId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Starts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSurebet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSurebet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Starts = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventId", wireType)
			}
			m.EventId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceId", wireType)
			}
			m.ServiceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServiceId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceId", wireType)
			}
			m.PriceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PriceId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSurebet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSurebet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSurebet(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSurebet
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSurebet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSurebet
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSurebet
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSurebet
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSurebet        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSurebet          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSurebet = fmt.Errorf("proto: unexpected end of group")
)
