/*
 * Sample API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dafapi

import (
	"encoding/json"
)

// DateTypeEnum the model 'DateTypeEnum'
type DateTypeEnum string

// List of DateTypeEnum
const (
	L DateTypeEnum = "l"
	T DateTypeEnum = "t"
	E DateTypeEnum = "e"
)

// Ptr returns reference to DateTypeEnum value
func (v DateTypeEnum) Ptr() *DateTypeEnum {
	return &v
}


type NullableDateTypeEnum struct {
	value *DateTypeEnum
	isSet bool
}

func (v NullableDateTypeEnum) Get() *DateTypeEnum {
	return v.value
}

func (v *NullableDateTypeEnum) Set(val *DateTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableDateTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableDateTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDateTypeEnum(val *DateTypeEnum) *NullableDateTypeEnum {
	return &NullableDateTypeEnum{value: val, isSet: true}
}

func (v NullableDateTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDateTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
